### ISSUE TITLE
Setup nodemailer to confirm user about submission of query.

### ISSUE THREAD

**Issue by Yash-Vijayvargiya** [JINDAL-JJ/UniVendor#1]
As soon as one submits a query on the "Contact us" page. The action is mentioned to store messages/queries into the database.
It is required to confirm with the user about the successful submission of the query by mail.
So setup "nodemailer" to mail to the provided email.

**Comment by Nirbhay1910** [comment]
Hi, pls assign this issue to me

**Comment by JINDAL-JJ** [comment]
@Nirbhay1910 go ahead and create a pull request in 4-5 days. Follow instructions provided in "README.md".

**Comment by Nirbhay1910** [comment]
okay sure, thanks @JINDAL-JJ
