### ISSUE TITLE
Create a system for pop-up.

### ISSUE THREAD

**Issue by Yash-Vijayvargiya** [JINDAL-JJ/UniVendor#2]
You need to show popup to confirm user about their sign-in/ sign-out or whenever a user submits a query on Contact Us page.
Use any library such as flash/noty, etc.

**Comment by khushi935** [comment]
I like to work on this. Can you please assign it to me?

**Comment by JINDAL-JJ** [comment]
@khushi935, go ahead and create the PR in 4-5 span. Remember to join the discord server provided in Readme.

**Comment by JINDAL-JJ** [comment]
@khushi935, go ahead and create the PR in 4-5 days. Remember to join the discord server provided in Readme.

**Comment by khushi935** [comment]
Okay

**Comment by abhinav5481** [comment]
Hi,
Is this issue still open? I would like to work on it. Please assign it to me.

**Comment by khushi935** [comment]
@abhinav5481  you can work on it. I am not able to do it.☹
