### ISSUE TITLE
Create whole backend for user while posting details of a product to sell.

### ISSUE THREAD

**Issue by JINDAL-JJ** [JINDAL-JJ/UniVendor#3]
Create a basic HTML form in the "views" folder named "sell_product.js" and pass its information into the database by setting up a controller following the route "/users/createPost". Also, change the schema of the product according to requirements under "/models/post.js". The form must include the name of product, type(books/electronics/other), images(max 3), expected price.
It will be required to set up the  "Multer" library to accept images of a product by a user. (for reference, you can take a look over commented portion in "controller/user_controller.js".

**Comment by abhinav5481** [comment]
Hi,
I would like to work on this. Could you please assign it to me?

**Comment by JINDAL-JJ** [comment]
Yeah, this issue is assigned to @abhinav5481, ensure to create a pull request in 4-5 days. Also, join discord server provided in Readme for further queries.
