### ISSUE TITLE
Create a Post form.

### ISSUE THREAD

**Issue by Shashank024** [JINDAL-JJ/UniVendor#4]
As soon as the user logs in, show a Sell button just on the right side of the search in the header which redirects to the Post form to give details of the product to sell (Make sure that the sell button redirect to the post form when the user is signed in on site)

![Screenshot (498)](https://user-images.githubusercontent.com/70697895/107372137-1a995200-6b0b-11eb-9892-3832b34ff9b1.png)

Create a different page to fill in details such as (Product Name, Product Type Product Image, Expected Price, etc ) using HTML, CSS, and bootstrap.
Also, attach the preview of the post form in the comments!

**Comment by Devenkapoor7303** [comment]
can i work on this issue

**Comment by JINDAL-JJ** [comment]
Before assigning I would like you to share the template that you would like to create for the post form.

**Comment by Devenkapoor7303** [comment]
Okay

**Comment by abhinav5481** [comment]
Hi Jatin,
I would like to work on this issue if it is still open. Please assign it to.

**Comment by JINDAL-JJ** [comment]
@abhinav5481 go ahead.
