### ISSUE TITLE
Integrate Welcome Bot 

### ISSUE THREAD

**Issue by muthuannamalai12** [JINDAL-JJ/UniVendor#7]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me as a part of Cross Woc.

**Comment by JINDAL-JJ** [comment]
@muthuannamalai12 go ahead.

**Comment by muthuannamalai12** [comment]
@JINDAL-JJ  For the custom message shown by the welcome bot we need a code of conduct. So for that reason I have opened a issue for code of conduct file. Kindly assign me that #11  issue.
